-- import which-key plugin safely
local status, which_key = pcall(require, "which-key")
if not status then
	return
end

-- configure which-key
which_key.setup()

-- add keybindings
which_key.register({
	["<leader>nh"] = "[N]o [H]ighlights",
	["<leader>wv"] = "Split [W]indow [V]ertically",
	["<leader>ws"] = "Split [W]indow [H]orizontally",
	["<leader>we"] = "Split [W]indow [E]qual width & height",
	["<leader>wx"] = "[W]indow close[X]",
	["<leader>to"] = "[T]ab [O]pen",
	["<leader>tx"] = "[T]ab [X]close",
	["<leader>tn"] = "[T]ab [N]ext",
	["<leader>tp"] = "[T]ab [P]revious",
	["<leader>wm"] = "Toggle [W]indow [M]aximization",
	["<leader>e"] = "Toggle file [E]xplorer",
	["<leader>?"] = "[?] Find recently opened files",
	["<leader><space>"] = "[ ] Find existing buffers",
	["<leader>/"] = "[/] Fuzzily search in current buffer",
	["<leader>sf"] = "[S]earch [F]iles",
	["<leader>sh"] = "[S]earch [H]elp",
	["<leader>sw"] = "[S]earch current [W]ord",
	["<leader>sg"] = "[S]earch by [G]rep",
	["<leader>sd"] = "[S]earch [D]iagnostics",
	["<leader>gc"] = "[G]it [C]ommits",
	["<leader>gfc"] = "[G]it [C]ommits for current [F]ile",
	["<leader>gb"] = "[G]it [B]ranches",
	["<leader>gs"] = "[G]it change[S]",
	["<leader>rs"] = "[R]e[S]tart LSP",
	["<leader>u"] = "Toggle [U]ndo tree",
	["gf"] = "[G]o re[F]erence",
	["gD"] = "[G]o to [D]eclaration",
	["gd"] = "[G]o de[F]inition",
	["gi"] = "[G]o to [I]mplementation",
	["<leader>ca"] = "[C]ode [A]ctions",
	["<leader>rn"] = "smart [R]e[N]ame",
	["<leader>D"] = "[D]iagnostics for line",
	["<leader>d"] = "[D]iagnostics for cursor",
	["[d"] = "[[]previous [D]iagnostic in buffer",
	["]d"] = "[]]next [D]iagnostic in buffer",
	["K"] = "Do[K]cumentation for what is under cursor",
	["<leader>o"] = "[O]utline on right hand side",
	["<leader>rf"] = "[R]ename [F]ile and update imports",
	["<leader>oi"] = "[O]rganize [I]mports",
	["<leader>ru"] = "[R]emove [U]nused variables",
	["<leader>a"] = "Sw[A]p next parameter",
	["<leader>A"] = "Sw[A]p previous parameter",
	["cs<current><new>"] = "[C]hange [S]urrounding",
	["ds<current><new>"] = "[D]elete [S]urrounding",
	["ys<current><new>"] = "[Y]ank [S]urrounding",
	["gr{motion}"] = "[G] [R]eplace with register",
	["]m"] = "Go to function.outer",
	["]]"] = "Go to class.outer",
	["]M"] = "Go to function.outer",
	["]["] = "Go to class.outer",
	["[m"] = "Go to function.outer",
	["[["] = "Go to class.outer",
	["[M"] = "Go to function.outer",
	["[]"] = "Go to class.outer",
	["aa"] = "@parameter.outer",
	["ia"] = "@parameter.inner",
	["af"] = "@function.outer",
	["if"] = "@function.inner",
	["ac"] = "@class.outer",
	["ic"] = "@class.inner",
	["cs{old}{new}"] = "[C]hange surround",
	["ds{toDelete}"] = "[D]elete surround",
	["ysiw{toAdd}"] = "Add around the hovered word",
})
